# Generated by Django 4.2.3 on 2024-03-03 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
