# Generated by Django 4.2.3 on 2024-03-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0003_imagegroup_remove_gallery_group_gallery_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='group',
            field=models.ManyToManyField(related_name='image', to='mypd.imagegroup'),
        ),
    ]
