# Generated by Django 4.2.3 on 2024-03-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0004_alter_gallery_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='group',
        ),
        migrations.DeleteModel(
            name='ImageGroup',
        ),
    ]
