# Generated by Django 4.2.3 on 2024-03-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0005_remove_gallery_group_delete_imagegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='group',
            field=models.ManyToManyField(related_name='image', to='mypd.imagegroup'),
        ),
    ]
