# Generated by Django 4.2.3 on 2024-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0013_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
