# Generated by Django 4.2.3 on 2024-04-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypd', '0015_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='testimony',
        ),
    ]
